# Generated by Django 5.2.1 on 2025-10-07 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('codigo', models.CharField(blank=True, default='', help_text='Opcional (código interno)', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Impresora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=80)),
                ('modelo', models.CharField(max_length=120)),
                ('nro_serie', models.CharField(max_length=120, unique=True, verbose_name='N° de serie')),
                ('conexion', models.CharField(choices=[('IP', 'IP'), ('USB', 'USB')], max_length=3)),
                ('ip', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('propiedad', models.CharField(choices=[('PROPIA', 'Propia'), ('ALQUILER', 'Alquiler')], max_length=8)),
                ('activa', models.BooleanField(default=True)),
                ('ubicacion', models.CharField(blank=True, default='', help_text='Ej: Administración, Depósito', max_length=120)),
                ('notas', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impresoras', to='inventario.sucursal')),
            ],
            options={
                'ordering': ['sucursal__nombre', 'marca', 'modelo'],
                'indexes': [models.Index(fields=['marca', 'modelo'], name='inventario__marca_b29e72_idx'), models.Index(fields=['sucursal', 'activa'], name='inventario__sucursa_36b41f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('conexion', 'USB'), models.Q(('conexion', 'IP'), models.Q(('ip', None), _negated=True)), _connector='OR'), name='impresora_ip_requerida_si_conexion_ip')],
            },
        ),
    ]
