# Generated by Django 5.2.1 on 2025-10-07 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('soporte', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impresora',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impresoras', to='soporte.sucursal'),
        ),
        migrations.AlterModelOptions(
            name='impresora',
            options={'ordering': ['sucursal__nombre', 'marca', 'modelo'], 'verbose_name': 'Impresora', 'verbose_name_plural': 'Impresoras'},
        ),
        migrations.RemoveConstraint(
            model_name='impresora',
            name='impresora_ip_requerida_si_conexion_ip',
        ),
        migrations.AddIndex(
            model_name='impresora',
            index=models.Index(fields=['nro_serie'], name='inventario__nro_ser_7e8f7b_idx'),
        ),
        migrations.AddIndex(
            model_name='impresora',
            index=models.Index(fields=['ip'], name='inventario__ip_553391_idx'),
        ),
        migrations.DeleteModel(
            name='Sucursal',
        ),
    ]
