# Generated by Django 5.2.1 on 2025-10-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_impresora_sucursal_alter_impresora_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impresora',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='IP / PC'),
        ),
    ]
