# Generated by Django 5.2.1 on 2025-10-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_impresora_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='impresora',
            name='toner',
            field=models.CharField(blank=True, default='', help_text='Modelo de tóner/cartucho', max_length=120),
        ),
    ]
