# Generated by Django 5.2.1 on 2025-07-07 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Categoría')),
            ],
            options={
                'verbose_name': 'Categoría de Problema',
                'verbose_name_plural': 'Categorías de Problema',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Estado de Ticket',
                'verbose_name_plural': 'Estados de Ticket',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Respuesta_pred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=2000, verbose_name='Título')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Nombre de la Sucursal')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('usuario_ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='IP del usuario')),
                ('imagen_error', models.ImageField(blank=True, null=True, upload_to='tickets/', verbose_name='Imagen del error')),
                ('motivo_anulacion', models.TextField(blank=True, null=True, verbose_name='Motivo de anulación')),
                ('motivo_reapertura', models.TextField(blank=True, null=True, verbose_name='Motivo de reapertura')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-fecha_creado'],
            },
        ),
        migrations.CreateModel(
            name='TicketImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='tickets/images/', verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemaComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre del problema')),
                ('codigo_error', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de error')),
                ('solucion', models.TextField(blank=True, null=True, verbose_name='Solución')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='problemas_comunes/', verbose_name='Imagen de error')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('fecha_actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='soporte.categoriaproblema', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Problema Común',
                'verbose_name_plural': 'Problemas Comunes',
                'ordering': ['nombre'],
            },
        ),
    ]
