# Generated by Django 5.2.1 on 2025-07-07 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soporte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_por_categoria', to='soporte.categoriaproblema', verbose_name='Categoría del problema'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='soporte.estadoticket', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='problema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_por_problema', to='soporte.problemacomun', verbose_name='Problema común'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sucursal',
            field=models.ForeignKey(db_column='sucursalid_ticket', on_delete=django.db.models.deletion.PROTECT, to='soporte.sucursal', verbose_name='Sucursal del ticket'),
        ),
       
    ]
