# Generated by Django 5.2.1 on 2025-07-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta_pred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=2000, verbose_name='Título')),
            ],
        ),
    ]
