# Generated by Django 5.2.1 on 2025-07-07 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0003_respuesta_pred'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='motivo_reapertura',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='problema',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='usuario_ip',
        ),
        migrations.AddField(
            model_name='ticketimage',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='soporte.ticket', verbose_name='Ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sucursal',
            field=models.ForeignKey(blank=True, db_column='sucursalid_ticket', null=True, on_delete=django.db.models.deletion.PROTECT, to='soporte.sucursal', verbose_name='Sucursal del ticket'),
        ),
    ]
